version: '3.4'

services: 
  jobproducer:
    build:
      context: .
      dockerfile: JobProducer/Dockerfile
    networks:
      - rabbitnetwork
    depends_on: 
      - "rabbitmq"

  jobconsumer:
    build:
      context: .
      dockerfile: JobConsumer/Dockerfile
    networks:
      - rabbitnetwork
    depends_on: 
      - "rabbitmq"

  rabbitmq:
    image: masstransit/rabbitmq:latest
    # volumes:
    #     - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
    #     - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
    #     - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    # environment:
    #   RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
    #   RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
    #   RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
        - 5672:5672
        - 15672:15672
    networks:
      - rabbitnetwork

networks:
  rabbitnetwork:
    driver: bridge